In [1]:
import numpy as np

### Numpy Array Operations

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing:", arr[2:7])

Basic Slicing: [3 4 5 6 7]


In [3]:
print("With Step", arr[1:7:2])

With Step [2 4 6]


In [4]:
print("Negative Indexing", arr[-3])

Negative Indexing 8


In [5]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Specific Element:",arr_2d[2,1])

Specific Element: 8


In [6]:
print("Entire row:",arr_2d[1])

Entire row: [4 5 6]


In [7]:
print("Entire column:",arr_2d[:,2])

Entire column: [3 6 9]


### Sorting

In [8]:
unsorted = np.array([3,1,2,4,7,9,5,6])
print("Sorted Array:", np.sort(unsorted))

Sorted Array: [1 2 3 4 5 6 7 9]


In [9]:
arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2d Array by column:",np.sort(arr_2d_unsorted, axis=0))

Sorted 2d Array by column: [[1 1]
 [2 2]
 [3 3]]


In [10]:
print("Sorted 2d Array by row:",np.sort(arr_2d_unsorted, axis=1))

Sorted 2d Array by row: [[1 3]
 [1 2]
 [2 3]]


### Filter

In [11]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_num = numbers[numbers % 2 == 0]
print("Even Number:", even_num)

Even Number: [ 2  4  6  8 10]


### Filter with Mask

In [12]:
mask = numbers > 5
print("Number greater than 5:",numbers[mask])

Number greater than 5: [ 6  7  8  9 10]


### Fancy Indexing vs np.where()

In [13]:
indices = [0,2,5]
print(numbers[indices])

[1 3 6]


In [15]:
where_result = np.where(numbers > 5)
print(numbers[where_result])

[ 6  7  8  9 10]


In [17]:
condition_arr = np.where(numbers > 5, numbers*4,numbers)
print(condition_arr)

[ 1  2  3  4  5 24 28 32 36 40]


### Adding and Removing Data

In [18]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combined = arr1+arr2
print(combined)


[5 7 9]


In [19]:
combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


In [20]:
original = np.array([[1,2], [3,4]])
new_row = np.array([[5,6]])
with_new_row = np.vstack((original,new_row))
print("Original Array:\n",original)
print("With new row:\n",with_new_row)

Original Array:
 [[1 2]
 [3 4]]
With new row:
 [[1 2]
 [3 4]
 [5 6]]


In [21]:
new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print("With new col:\n",with_new_col)


With new col:
 [[1 2 7]
 [3 4 8]]


In [22]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print("Array after deletion:",deleted)

Array after deletion: [1 2 4 5]
