In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [2]:
import sys
print(sys.executable)


/Library/Developer/CommandLineTools/usr/bin/python3


In [1]:
import numpy as np
print(np.__version__)

2.0.2


In [2]:
Array

NameError: name 'Array' is not defined

Array

In [3]:
import numpy as np

arr = np.array([1,2,3])

In [4]:
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6]])
print(arr)                

[[1 2 3]
 [4 5 6]]


Array Properties

In [5]:
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape", arr.shape)
print("Dimension", arr.ndim)
print("Size", arr.size)
print("DType", arr.dtype)                

Shape (2, 3)
Dimension 2
Size 6
DType int64


Array Reshaping


In [9]:
import numpy as np

new_arr = np.arange(12)
print("Original Array: \n", new_arr)

reshaped = new_arr.reshape((3,4))
print("Reshaped Array: \n", reshaped)

flattened = reshaped.flatten()
print("Flattened Array: \n", flattened)

raveled = reshaped.ravel()
print("Ravelled Array: \n", raveled)


Original Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Ravelled Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
